# Generated by Django 4.0.4 on 2022-05-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=20)),
                ('isTrending', models.BooleanField(default=False)),
                ('isBookmarked', models.BooleanField(default=False)),
                ('thumbnail', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=16)),
                ('last_login', models.DateTimeField()),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('show_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_id_activity', to='entertainment_app.show')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_activity', to='entertainment_app.user')),
            ],
        ),
    ]
